api_key: "!!mys3_api_key"
public_base_url: "!!mys3_public_base_url"
storage_root: "!!mys3_storage_root"
max_upload_size_mb: !!mys3_max_upload_size_mb
follow_symlinks: !!mys3_follow_symlinks
bind_host: "!!mys3_bind_host"
port: !!mys3_port
puma_threads_min: !!mys3_puma_threads_min
puma_threads_max: !!mys3_puma_threads_max
log_level: "!!mys3_log_level"
log_file: "!!mys3_log_file"
timezone: "!!mys3_timezone"
